### PR TITLE
[bug fix] remove useless walk function to resolve 'not found #root el…

### PR DESCRIPTION
**Pull request by erha19**
The default config of weex project create by `weex-toolkit` will generate entry config automatically, but this project has already used `entry.js` as entry config in webpack, so the `walk` function needs to be removed, and I also remove the useless code in the webpack config.
It works fine on my platform, please to have a review of this changes!

### CODE REVIEW

**Comment by NoraGithub** [comment]
@erha19 Thanks for rapid feedback.

I read the  official sample project `hackernews` and found that the structures of both two project are similar. The `entry.js` is not generated by ` weex-toolkit`, but configured in the webpack config, like `entry:'./src/main.js}' ` or `entry:{index:'entry.js'}`

If default config of weex project is created by `weex-toolkit` ,where  the content of `entry.js`,like the global router、component and so on , should be placed? 

I am also developing my own project, so it would be great if it can be answered.

**Comment by erha19** [comment]
@NoraGithub There should be an example of weex best practices, the routing mechanism is a very important part of developing a complete application, but using the router like `yanxuan-weex-demo` or `hackernews`  is only a temporary solution. 

After a busy time, the weex team will devise a routing system that better matches front-end development and takes advantage of native performance benefits.

After that, I will rewrite the weex project generated by `weex-toolkit`, so if you want to develop now, you should modify your code like this project to manage your page router.

**Comment by NoraGithub** [comment]
@erha19 Thanks. It helps a lot.

**Comment by zwwill** [comment]
wow！I do looking forward to the new routing system.

**Pull request merged**
