### PR TITLE
[bug fix] update webpack config and lock package dependences.

### PR DESCRIPTION
**Pull request by erha19**
Hi~ @zwwill

I find some wrong with your project while running `npm run dev & npm run serve`, I made some changes to solve this problem: 

- Update webpack config to fix `ERROR in index.web.js from UglifyJs` error.
- unignore package-lock.json to make sure install the same version of `vue` and `vue-template-compiler` which may cause `vue dismatch` error. And I also add some new package for `webpack` and remove useless package from the project.

### CODE REVIEW

**Comment by zwwill** [comment]
thx , I really appreciate it !

**Comment by zwwill** [comment]
sorry, after merging, I find something also wrong, such as, `ERROR in index.web.js from UglifyJs`.
maybe sometime, I go to check it. I do very  busy lately

**Comment by erha19** [comment]
@zwwill maybe you should remove your `node_modules` and install npm package via `npm install `again, the` package-lock.json` file does not work while you just add it to your project then run `npm install`.

**Comment by zwwill** [comment]
@erha19 I reclone the project, errors still exist

**Comment by NoraGithub** [comment]
@zwwill 
Before this commit, I also met the `ERROR in index.web.js from UglifyJs` issue. But now, it's solved.
I also reclone the project now, and It works well for me. I guess the global env variable matters?

$ npm list -g -depth=0
/Users/NoraChan/.nave/installed/weex/lib
├── npm@5.5.1
└── weex-toolkit@1.1.0-beta.6

npm ERR! missing: loader-utils@^1.1.0, required by vue-loader@12.2.0
npm ERR! peer dep missing: webpack@1 || 2 || ^2.1.0-beta || ^2.2.0-rc, required by babel-loader@6.4.1

Hope it helps.
One more thing, thanks for your great job of this repo.

**Comment by zwwill** [comment]
@erha19 You're right，I changed my version of node, then, rebuild, `ERROR in index.web.js from UglifyJs` didn't  appear again. thx.

**Pull request merged**
